# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: 'v0.4.4'
    hooks:
    -   id: ruff-format # Runs the formatter
    -   id: ruff        # Runs the linter
        args: [--fix, --exit-non-zero-on-fix]

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.10.0'
    hooks:
    -   id: mypy