name: Code Quality Checks

    on:
      push:
        branches: ["main", "develop"]

    jobs:
      lint_and_test:
        runs-on: ubuntu-latest # Use the latest Ubuntu runner

        strategy:
          matrix:
            python-version: ["3.10", "3.11"]

        steps:
          # 1. Get the code from the repository
          - name: Check out code
            uses: actions/checkout@v4

          # 2. Set up the specified Python version
          - name: Set up Python ${{ matrix.python-version }}
            uses: actions/setup-python@v5
            with:
              python-version: ${{ matrix.python-version }}

          # 3. Install dependencies (including dev dependencies)
          - name: Install dependencies
            run: |
              python -m pip install --upgrade pip
              pip install .[dev] # Installs package and dev dependencies

          # 4. Run Ruff Formatter
          - name: Check formatting with Ruff
            run: ruff format --check .

          # 5. Run Ruff Linter
          - name: Lint with Ruff
            run: ruff check .

          # 6. Run MyPy Type Checker
          - name: Check types with MyPy
            run: mypy .

          # 7. Run Pytest
          - name: Run tests with Pytest
            run: pytest